// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK1UmjcKl2gZNSubqN-Pm_O9bK8Aok8I4',
    appId: '1:735198867520:web:841df5974870226614efa5',
    messagingSenderId: '735198867520',
    projectId: 'palcuero',
    authDomain: 'palcuero.firebaseapp.com',
    storageBucket: 'palcuero.firebasestorage.app',
    measurementId: 'G-ZR82XM6LHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABSS_Q8v5MR4tAOnif8DcDwUp_9iEeK7o',
    appId: '1:735198867520:android:4e3d8a42909fdd5614efa5',
    messagingSenderId: '735198867520',
    projectId: 'palcuero',
    storageBucket: 'palcuero.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4bPTKJKsKAffbW18Dhn2bdyw17XbRoYw',
    appId: '1:735198867520:ios:b03731cb7c24078414efa5',
    messagingSenderId: '735198867520',
    projectId: 'palcuero',
    storageBucket: 'palcuero.firebasestorage.app',
    iosBundleId: 'com.example.palCuero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4bPTKJKsKAffbW18Dhn2bdyw17XbRoYw',
    appId: '1:735198867520:ios:b03731cb7c24078414efa5',
    messagingSenderId: '735198867520',
    projectId: 'palcuero',
    storageBucket: 'palcuero.firebasestorage.app',
    iosBundleId: 'com.example.palCuero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK1UmjcKl2gZNSubqN-Pm_O9bK8Aok8I4',
    appId: '1:735198867520:web:af8a334614e1097b14efa5',
    messagingSenderId: '735198867520',
    projectId: 'palcuero',
    authDomain: 'palcuero.firebaseapp.com',
    storageBucket: 'palcuero.firebasestorage.app',
    measurementId: 'G-TVPF8NXHPY',
  );

}